[package]
name = "define3"
version = "0.1.0"
authors = ["neynt <hyriodula@gmail.com>"]

[dependencies]
colored = "~1"
dirs = "~1"
getopts = "~0"
nom = "~6"
quick-xml = "~0"
regex = "~1"
rusqlite = "~0"
textwrap = "~0"
